version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
  - source: server_clear.sh
    destination: /home/ec2-user/server
  - source: fix_privileges.sh
    destination: /home/ec2-user/server
  - source: server_start.sh
    destination: /home/ec2-user/server
  - source: server_stop.sh
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: ec2-user
