version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html   # Adjust destination directory as needed

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/fix_privileges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationRestart:
    - location: scripts/restart_server.sh
      timeout: 20
      runas: ec2-user
