version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18

    commands:
      - cd s30project
      - mvn clean install
      - cd ../fitnessapp
      - npm install
            
  build:
    commands:                               
      - cd ../s30project
      - mvn clean install
      - cd ../fitnessapp
      - npm run build
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - s30project/target/*.jar                    
    - fitnessapp/public/**/*
    - fitnessapp/src/**/*
    - fitnessapp/package.json
    - appspec.yml
    - scripts/**/*.sh                 
